### PR TITLE
Move UI task progress bar during START DC proc

### PR DESCRIPTION
**Pull request by DavidePrincipi**
The START DC procedure downloads and install the nsdc chroot and takes a lot of time. During installation the progress bar is stuck at 0%. 

This PR moves the progress bar and gives some kind of feedback to the user while he's waiting.

### CODE REVIEW

**Comment by DavidePrincipi** [comment]
In nethserver-testing:
nethserver-dc-1.0.7-1.3.gfac89e9.ns7.x86_64.rpm

**Comment by stephdl** [comment]
i'm on it

**Comment by stephdl** [comment]
- tested on a full ns7rc updated

[root@NS7DEV2 ~]# cat /etc/nethserver-release 
NethServer release 7.2.1511 (rc2)

- installed the version of nethserver-dc from nethserver-testing

[root@NS7DEV2 ~]# rpm -qa nethserver-dc 
nethserver-dc-1.0.7-1.3.gfac89e9.ns7.x86_64

- you can see the full event at : https://gist.github.com/stephdl/fd6c1d0c14779be95a267a182c9508b3

The event showed progresses, only the step of adjust-service is a bit long. It looks stopped at 57%

in the gist files we can see errors 

https://gist.github.com/stephdl/fd6c1d0c14779be95a267a182c9508b3#file-gistfile1-txt-L1279
https://gist.github.com/stephdl/fd6c1d0c14779be95a267a182c9508b3#file-gistfile1-txt-L1379
https://gist.github.com/stephdl/fd6c1d0c14779be95a267a182c9508b3#file-gistfile1-txt-L1391
https://gist.github.com/stephdl/fd6c1d0c14779be95a267a182c9508b3#file-gistfile1-txt-L1822


Exept the errors in the gist file (which are not relevant with the code change i guess) the purpose is verified

**Comment by DavidePrincipi** [comment]
Thank you for your test @stephdl ! I agree those error messages are not relevant and shouldn't be symptoms of real problems.

**Pull request merged**
